-- MySQL Script generated by MySQL Workbench
-- 09/14/21 16:41:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema assisplan
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema assisplan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `assisplan` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `assisplan` ;

-- -----------------------------------------------------
-- Table `assisplan`.`classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assisplan`.`classe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC),
  UNIQUE INDEX `abbreviation_UNIQUE` (`abbreviation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assisplan`.`cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assisplan`.`cours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `intitule` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `intitule_UNIQUE` (`intitule` ASC),
  UNIQUE INDEX `abbreviation_UNIQUE` (`abbreviation` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assisplan`.`enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assisplan`.`enseignant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomcomplet` VARCHAR(255) NOT NULL,
  `qualification` VARCHAR(255) NOT NULL,
  `annee_debut` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `nomcomplet_UNIQUE` (`nomcomplet` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `assisplan`.`horaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `assisplan`.`horaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jour` ENUM('lundi', 'mardi', 'mercredi', 'jeudi', 'vendredi', 'samedi', 'dimanche') NOT NULL,
  `quantiemeheure` ENUM('1', '2', '3', '4', '5', '6', '7', '8') NOT NULL,
  `anneedebut` INT NOT NULL,
  `anneefin` INT NOT NULL,
  `classe_id` INT NOT NULL,
  `cours_id` INT NOT NULL,
  `enseignant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_horaire_classe_idx` (`classe_id` ASC),
  INDEX `fk_horaire_cours1_idx` (`cours_id` ASC),
  INDEX `fk_horaire_enseignant1_idx` (`enseignant_id` ASC),
  UNIQUE INDEX `plan_heure_UNIQUE` (`quantiemeheure` ASC, `classe_id` ASC, `jour` ASC),
  UNIQUE INDEX `plan_enseignant_UNIQUE` (`jour` ASC, `quantiemeheure` ASC, `enseignant_id` ASC),
  CONSTRAINT `fk_horaire_classe`
    FOREIGN KEY (`classe_id`)
    REFERENCES `assisplan`.`classe` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_horaire_cours1`
    FOREIGN KEY (`cours_id`)
    REFERENCES `assisplan`.`cours` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_horaire_enseignant1`
    FOREIGN KEY (`enseignant_id`)
    REFERENCES `assisplan`.`enseignant` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
